Se comento la linea que pide confirmacion al action de destroy

diff --git a/.github/workflows/terraform-destroy.yml b/.github/workflows/terraform-destroy.yml
--- a/.github/workflows/terraform-destroy.yml
+++ b/.github/workflows/terraform-destroy.yml
@@ -25,11 +25,11 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Confirm destroy
-        if: ${{ github.event.inputs.confirm != 'DESTROY' }}
-        run: |
-          echo "❌ Confirmation failed"
-          exit 1
+      # - name: Confirm destroy
+      #   if: ${{ github.event.inputs.confirm != 'DESTROY' }}
+      #   run: |
+      #     echo "❌ Confirmation failed"
+      #     exit 1
 
       - name: Upload Configuration
         id: upload
